### ISSUE TITLE
tello video not working 

### ISSUE THREAD

**Issue by theman162** [johnwalicki/Node-RED-DroneViewer#1]
i followed the steps but the tello video is not working it keep showing local host cannot connect

**Comment by johnwalicki** [comment]
@theman162 - Did you open the 11111/udp port on your firewall?

**Comment by axdonlee** [comment]
follow all steps but still unable to stream the video. keep showing local host cannot be connected

**Comment by johnwalicki** [comment]
@theman162 @axdonlee   The flows in this repo only take still photos. It demonstrates how to display the pictures in the dashboard and send the images to Watson Visual Recognition for classification. If you want to stream video, you need to follow the instructions in another repo https://github.com/johnwalicki/Node-RED-DroneViewer

**Comment by johnwalicki** [comment]
@axdonlee  Oh - we're in that repo. My mobile and lack of coffee has confused me. I tested this flow last night, it works fine. 

Are you running 'npm start' to run the node server on port 3000?

**Comment by johnwalicki** [comment]
@axdonlee Which OS are you running? Can you confirm that the firewall allows traffic on the 11111/udp port?

**Comment by axdonlee** [comment]
i did followed the instruction.  I am running on window 8. I have disable my firewall but how do i allow traffic on the 11111/udp. How do i set up that?

**Comment by johnwalicki** [comment]
@axdonlee  I've been a Linux desktop user for the past 22 years so have never run Windows.  This article has Windows networking instructions - https://blogs.msdn.microsoft.com/mandi/2014/11/03/how-to-create-a-windows-firewall-inbound-rule/

**Comment by theman162** [comment]
I managed to fix the problem.Downloaded the wrong ffmpeg file.

**Comment by axdonlee** [comment]
Hi

Anything we need to redo in order to get the video streaming?

**Comment by johnwalicki** [comment]
@theman162  - Glad to hear that you have installed the prerequisites correctly. I propose that I close this issue.
