### ISSUE TITLE
Video Link broken in README

### ISSUE THREAD

**Issue by jsolderitsch** [johnwalicki/Node-RED-DroneViewer#2]
This link:
[]https://github.com/johnwalicki/Node-RED-DroneViewer/blob/master/flows/Node-RED-Tello-VideoStream-Control-Dashboard.json
gives a 404 error.
The link is found in the main README for this repo.

**Comment by johnwalicki** [comment]
@jsolderitsch  Thanks for the report. I have added that flow to the /flows directory.  It was in another branch. Closing issue.
